[workspace]
resolver = "2"
members = ["server"]
[workspace.dependencies]
rust_decimal = { version = "1.33.1", features = [
  "serde-str",
  "serde-with-arbitrary-precision",
] }
tokio = { version = "1.26.0", features = ["full"] }
futures = "0.3.27"
dashmap = { version = "5.4.0", features = ["serde"] }
ctrlc = "3.2.5"
serde = { version = "1.0", features = ["derive"] }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

tower = { version = "0.4", features = [
  "util",
  "timeout",
  "load-shed",
  "limit",
] }
tower-http = { version = "0.4.3", features = ["cors", "trace"] }
async-trait = "0.1.68"
once_cell = "1.18.0"
hyper = { version = "0.14.14", features = ["stream"] }
tokio-stream = "0.1.11"
async-channel = "1.8.0"
tokio-tungstenite = "0.17.0"
anyhow = "1.0.66"
prost-types = "0.11.2"
serde_json = "1.0"
strum = { version = "0.26.1", features = ["derive"] }
lazy_static = "1.4.0"
dotenvy = "0.15.6"
rand = "0.8.5"
ts-rs = "6.2.1"
garde = "0.11.2"
axum_garde = "0.11.2"
uuid7 = { version = "0.3.3" }
reqwest = "0.11.18"
log = "0.4.19"
axum = { version = "0.6.12", features = ["ws", "macros"] }
axum-server = { version = "0.5", features = ["tls-rustls"] }
axum-macros = "0.3.7"
